--[[ This Source Code Form is subject to the terms of the Mozilla Public
     License, v. 2.0. If a copy of the MPL was not distributed with this
     file, You can obtain one at https://mozilla.org/MPL/2.0/. ]]

-- This code is based on the "input keys" example by raysan5, available at: https://www.raylib.com/examples.html

require 'examples/core/2d-camera'
require 'examples/core/2d-camera-platformer'
require 'examples/core/3d-camera-first-person'
require 'examples/core/3d-camera-free'
require 'examples/core/3d-camera-mode'
require 'examples/core/3d-picking'
require 'examples/core/basic-window'
require 'examples/core/drop-files'
require 'examples/core/input-gamepad'
require 'examples/core/input-keys'
require 'examples/core/input-mouse'
require 'examples/core/input-mouse_wheel'
require 'examples/core/loading-thread'
require 'examples/core/random-values'
require 'examples/core/scissor-text'
require 'examples/core/storage-values'
require 'examples/core/vr-simulator'
require 'examples/core/window-letterbox'
require 'examples/core/world-screen'

require 'examples/shapes/logo-raylib-nelua'
